language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t frostvlad/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true frostvlad/docker-react npm run test